import { test, expect } from '@playwright/test';

test('visitor completes three workflows and resets their private club',async ({page},testInfo) => {
  const errors: string[] = [];
  page.on('pageerror',error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button',{name:'Try interactive demo'}).focus();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('heading',{name:'Explore a fictional Weiqi club'})).toBeVisible();
  await expect(page.getByText('Demo Organiser - organiser@example.com')).toBeVisible();
  await expect(page.getByText('14 active, 0 inactive')).toBeVisible();
  await page.screenshot({path:testInfo.outputPath('dashboard.png')});
  await page.getByRole('button',{name:/01 · Run a tournament/}).click();
  await expect(page.getByRole('heading',{name:'Demo Club Cup',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Open Tournament Engine'}).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  const finalMatch = dialog.locator('article').filter({hasText:'R2 - Table 4'});
  await finalMatch.getByRole('combobox').selectOption('White Win');
  await expect(dialog.getByText('Updating standings...')).toBeHidden();
  await dialog.getByRole('button',{name:'Standings',exact:true}).click();
  await expect(dialog.getByRole('table')).toBeVisible();
  await page.screenshot({path:testInfo.outputPath('tournament.png')});
  await dialog.getByRole('button',{name:'Pairings',exact:true}).click();
  await dialog.getByRole('button',{name:/Generate.*Round/}).click();
  await expect(dialog.getByText('R3 - Table 1')).toBeVisible();
  await dialog.getByRole('button',{name:'Close',exact:true}).click();
  await expect(page.getByText('Round 2 results complete',{exact:false})).toBeVisible();
  await page.getByRole('button',{name:/02 · Manage a signup/}).click();
  await page.getByRole('combobox',{name:'Demo persona'}).selectOption('member');
  await expect(page.getByText('Demo Member - member0@example.com')).toBeVisible();
  const workshop = page.locator('article.event-card').filter({hasText:'Beginner Workshop'});
  await workshop.getByRole('button',{name:'Register',exact:true}).click();
  await expect(workshop.getByRole('button',{name:'Pending Approval'})).toBeVisible();
  await workshop.screenshot({path:testInfo.outputPath('signup.png')});
  await page.getByRole('combobox',{name:'Demo persona'}).selectOption('organiser');
  await page.getByRole('link',{name:'Members',exact:true}).click();
  await page.locator('button.member-card-toggle').filter({hasText:'Demo Member'}).click();
  const signup = page.locator('.member-registration-row').filter({hasText:'Beginner Workshop'});
  await signup.getByRole('button',{name:'Approve',exact:true}).click();
  await expect(signup.getByText('Registered',{exact:true})).toBeVisible();

  await page.getByRole('button',{name:/03 · Resolve an attendance request/}).click();
  const correction = page.locator('article[data-demo-highlight="true"]');
  await expect(correction.getByText('Demo Member',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Dismiss notification',exact:true}).all().then(async (items) => { for (const item of items) await item.click(); });
  await page.screenshot({path:testInfo.outputPath('attendance.png')});
  await correction.getByRole('button',{name:'Approve',exact:true}).click();
  await expect(page.getByText(/Decision: Approved/)).toBeVisible();
  await expect(page.getByRole('button',{name:'Replace',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Reset demo',exact:true}).click();
  await page.getByRole('button',{name:'Yes, reset demo'}).click();
  await expect(page.getByText(/Member signup: Not registered/)).toBeVisible();
  await expect(page.getByText(/Decision: Pending/)).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByRole('combobox',{name:'Demo persona'})).toBeVisible();
  await page.screenshot({path:testInfo.outputPath('mobile.png'),fullPage:true});
  const overflow = await page.evaluate(() => Array.from(document.querySelectorAll('*')).filter(el => el.getBoundingClientRect().right > innerWidth + 1).slice(0,12).map(el => ({tag:el.tagName,cls:el.className,right:el.getBoundingClientRect().right})));
  expect(overflow).toEqual([]);
  expect(errors).toEqual([]);
});

test('entry shows a recoverable capacity failure',async ({page}) => {
  await page.route('**/api/demo/session',route => route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'All demo spaces are busy. Please try later or view the portfolio walkthrough.'})}));
  await page.goto('/');
  await page.getByRole('button',{name:'Try interactive demo'}).click();
  await expect(page.getByRole('alert')).toContainText('All demo spaces are busy');
  await expect(page.getByRole('button',{name:'Try interactive demo'})).toBeEnabled();
  await expect(page.getByRole('link',{name:'View project walkthrough'})).toBeVisible();
});
